Adding changes for 10.80
lirantal/operations-orchestration-api pull request #36
Opened 2018-04-03 05:57 UTC by mfreeman451

Fixed a bug that was preventing this from working with OO 10.80, added ability to get execution summary from OO API

2018-04-03 10:06 UTC, lirantal commented
@mfreeman451 Thank you for your first contribution!
Could you please fix the lint issues that the build fails on so I can merge it? https://travis-ci.org/lirantal/operations-orchestration-api/builds/361491334?utm_source=github_status&utm_medium=notification

2018-04-03 10:06 UTC, lirantal requested changes

2018-04-03 10:06 UTC, lirantal commented on lib/Executions.js
> +	async executionSummary (flowid, cb) {
can you please update the indentations to match the file standards? (i.e: 2 spaces)

2018-04-09 15:21 UTC, mfreeman451 reviewed
Updated, do I just generate a new pull request?

2018-04-09 15:23 UTC, mfreeman451 commented
Fixes in place, how to proceed?

2018-04-09 18:32 UTC, lirantal commented
@mfreeman451 can you take a look at why the tests fail now?
https://travis-ci.org/lirantal/operations-orchestration-api/builds/364170715?utm_source=github_status&utm_medium=notification

2018-04-09 21:36 UTC, mfreeman451 commented
Updated test.js

2018-04-10 16:43 UTC, lirantal commented
@mfreeman451 are you sure you pushed the relevant update?
the test still fails - check it out here: https://travis-ci.org/lirantal/operations-orchestration-api/builds/364330226?utm_source=github_status&utm_medium=notification

2023-10-27 11:04 UTC, lirantal commented
Closing due to stale PR but if you want to get back at it @mfreeman451 please open a new one and I'll be happy to merge quickly.

2023-10-27 11:04 UTC, closed without merging